#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

feh --bg-fill -no-fehbg $XDG_CONFIG_HOME/bg4.jpg &
$XDG_CONFIG_HOME/bspwm/panel &

bspc config presel_feedback_color  "#FB4934"
bspc config focused_border_color "#B8BB26"
bspc config normal_border_color  "#928374"
bspc config active_border_color  "#928374"
bspc config urgent_border_color  "#FB4934"

bspc config border_width         2
bspc config window_gap          12
#bspc config top_padding         20
#bspc config initial_polarity     second_child

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# auto split the focused node east
#bspc rule -a \* node=focused split_dir=east

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a jumanji desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
